pull_request_rules:
- name: metworkbot automerge
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
  conditions:
    - author=metworkbot
- name: integration branch
  actions:
    merge:
      method: squash
      strict: true
    delete_head_branch: {}
  conditions:
    - base=integration
    - label!=no-mergify
    - '#approved-reviews-by>=1'
